### ISSUE TITLE
Extra padding around long Value text.

### ISSUE THREAD

**Issue by ahogen** [jongracecox/anybadge#14] opened 2019-05-17 20:40 UTC
Love the library. Been using it a lot!

I recently had a need/desire to put a long piece of text in a badge and found that there was lots of padding around the value.

### What I wanted:

- Badge width: about 280
- Text X: about 170

![expected](https://user-images.githubusercontent.com/6827790/57954770-b94a3d80-78a8-11e9-9ee9-e4d1b8394db7.PNG)

### What `anybadge` actually made:

- Badge width: 357
- Text X: 210

![actual](https://user-images.githubusercontent.com/6827790/57954802-d2eb8500-78a8-11e9-87a7-f27ebc6d55ea.PNG)

### What I wrote:

```python
badge = anybadge.Badge(label='CppCheck',
                       value='err: 2 | warn: 9 | info: 99 | style: 365',
                       default_color='red',
                       num_padding_chars=0)

badge.write_badge('cppcheck.svg', overwrite=True)
```

Any way to get rid of the extra whitespace?

Cheers!

**Comment by njalerikson** [comment] 2019-05-23 12:48
This appears to have been addressed by this fork by @elbosso:
https://github.com/elbosso/anybadge/issues/1

Maybe that change can be merged back into this project?

**Comment by ahogen** [comment] 2019-05-29 18:40
Sorry, I checked for open issues, but not PRs.

I took a look at the suggested change. I agree with your comment about how requiring `matplotlib` seems like a lot to ask. I personally am not a fan of having to include fairly large math libraries just to use a font collection. And then separately use a large `Pillow` library. 

On the flip side, I wasn't able to come up with anything better. I was playing around with using [`dot`]( ) instead and came up with this...

```
digraph shieldbadge {
    abc [shape=none, margin=0, label=<
    <table border="0" cellborder="0" cellspacing="0" cellpadding="3">
        <tr>
            <td bgcolor="#333333"><font point-size="9" face="DejaVu Sans,Verdana,Geneva,sans-serif" color="white">CppCheck</font></td>
            <td bgcolor="#E03d44"><font point-size="9" face="DejaVu Sans,Verdana,Geneva,sans-serif" color="white">this is a long block of text!</font></td>
        </tr>
    </table>>];
}
```

Which can be rendered as an SVG with `dot -Tsvg -o ./badge.svg ./badge.dot` and looks like...

![testbadge](https://user-images.githubusercontent.com/6827790/58582397-7f612b80-8206-11e9-9cc7-35a71a742658.PNG)


... but that's just a long way of saying that I don't know how else to properly fix the width. :disappointed:

**Comment by jongracecox** [comment] 2019-06-01 03:07
Thanks for the feedback, and sorry about the late reply.

As you can probably see from the code I'm just doing a simple multiplication of an approximate font width to get the total badge width, and that's just not accurate with variable width fonts.  I feel like my options boil down to:

- Use an external library to handle width calculation
- Write something that approximates a bit more accurately
- Add some manual options to adjust the badge width (not very nice, not very dynamic, but would help your situation)

As discussed, I've held off merging the matplotlib PR because I'm still on the fence about whether to add that as a hard dependency.  I wondered about creating two versions:

- `anybadge` - This light-weight version which can't do advanced stuff with fonts.
- `anybadge[matplotlib]` - The more advanced version which can use more fonts is more accurate with width calculations.

If I did that, which one would you pick?  Personally I like the simplicity and small size of the current implementation, so I would probably still use the basic one for my stuff.

One thing I've been considering is using a list of "thin" characters so calculating the width is more accurate.  I will have a play with that and see if I can get it working better.

**Closed** 2019-06-01 07:42 UTC

**Comment by jongracecox** [comment] 2019-06-01 08:25
I have just cut [anybadge release 1.2.0](https://pypi.org/project/anybadge/1.2.0/), which you can install now with `pip install "anybadge==1.2.0"`.

I added a dictionary containing sets of characters along with the percentage of the full font width that they use.  This is a simple but effective way to be more accurate with width calculations.  The results might not be perfect, but I hope they will be nice enough until I can spend more time refining this.  You can [review the function here](https://github.com/jongracecox/anybadge/blob/aa4977bcf802a42e4e67778f1ae3dd29db2807b5/anybadge.py#L409).

I also added [unittests](https://github.com/jongracecox/anybadge/blob/master/tests/test_anybadge.py) to the project so that these things can be more easily tested.

Here is your first example, but without `num_padding_chars=0` (you shouldn't be required to use this to get good looking results)

![image](https://user-images.githubusercontent.com/30441316/58745810-18b95900-8424-11e9-8c3d-8a4b4cea960d.png)

Here is your example **with** the `num_padding_chars=0`:

![image](https://user-images.githubusercontent.com/30441316/58745829-7057c480-8424-11e9-8023-e6ed8b1b97bf.png)

This is without any additional package dependencies, so still maintaining a minimal code line.  I can probably refine it a bit more if you feel like there should still be less padding, however I feel happy with the results.

Please re-open this if you have still feel like changes are needed.

**Comment by ahogen** [comment] 2019-06-04 19:07
Ooh hey cool! That is better. 

Looking at the code, I don't know if I like that the original fixed width size is mixed with the new proportional width calculation stuff. I'm looking in `label_width()` and `value_width()` functions. Maybe it's somewhere else too.

I guess I feel like if we're padding by characters, then use the same numbers for character width. Otherwise, maybe pad by pixels? I find it odd that if I set `num_padding_chars=-0.5`, the label gets squashed but the value doesn't. But this is probably another issue.

After raising this issue here, I found (re-discovered) [Shields.io](https://shields.io/). I think their implementation is all JavaScript, but here's a comparison. `anybadge` v1.4.0 is on the left. And [here's the code](https://gist.github.com/ahogen/9a088b426c8f93b22ecf3f8608d30739).

![anybadge_vs_shieldsio](https://user-images.githubusercontent.com/6827790/58906370-99948100-86c0-11e9-99fb-f86a72fe2de8.PNG)


I found that I got pretty close to the Shields.io version when I changed the following two sizes to be slightly smaller. 

```python
char_width_percentages = {
    "lij|' ": 30.0,

    'aebdhnopqug#$L+<>=?_~FZT0123456789': 60.0,
}
```

![anybadge_vs_shieldsio_2](https://user-images.githubusercontent.com/6827790/58906629-36571e80-86c1-11e9-9a12-40030bcffa08.png)

**Comment by jongracecox** [comment] 2019-06-22 05:03
@ahogen, I've just issued another PR (#24) that aims to make the widths more in line with what gets created by shields.io.  I haven't touched the `char_width_percentages` dict because that's actually generated using matplotlib, and should actually be pretty accurate.  I think the issue is actually to do with a `+3` that appears in the badge width calculation.  This is there because without it the characters touch each end of their boundaries.  I've reduced this to `2` and it gives a narrower badge.  I tested reducing to 1 and it's too close, so I think 2 is good.  The other thing I did was set the default padding character count to `0`, which I think it what everyone seems to want (shout if not).
